# Generated by Django 2.2.24 on 2021-07-10 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='responsibles',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
