# Generated by Django 2.2.24 on 2021-07-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_checklist', '0002_itemchecklist_responsibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_checklist', to='cards.Card'),
        ),
    ]
