# Generated by Django 2.2.24 on 2021-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_checklist', '0003_auto_20210711_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
