# Generated by Django 2.2.24 on 2021-07-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_checklist', '0004_auto_20210713_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchecklist',
            name='due_to',
        ),
    ]
