# Generated by Django 2.2.24 on 2021-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_checklist', '0005_remove_itemchecklist_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklist',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
