# Generated by Django 2.2.24 on 2021-07-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='Workspace',
            new_name='workspace',
        ),
    ]
