# Generated by Django 2.2.24 on 2021-07-13 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210712_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
