# Generated by Django 2.2.24 on 2021-07-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
