# Generated by Django 2.2.24 on 2021-07-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210711_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='board',
        ),
        migrations.AddField(
            model_name='notification',
            name='template_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
